export const MOCK_PIECES = [
  {
    id: '1',
    title: 'Sage Dresser',
    slug: 'sage-dresser',
    piece_type: 'Mid-century dresser',
    category: 'colour',
    price_zar: 4500,
    status: 'available',
    year: '2025',
    materials: 'Oak, sage paint, brass hardware',
    dimensions: { width_cm: 120, height_cm: 180, depth_cm: 60 },
    description: 'A beautiful mid-century dresser restored with soft sage paint.',
    before_image: { url: 'https://picsum.photos/seed/before-dresser/800/1000' },
    after_images: [
      { image: { url: 'https://picsum.photos/seed/after-dresser/800/1000' } },
      { image: { url: 'https://picsum.photos/seed/after-dresser-detail/800/1000' } },
    ],
    featured: true,
  },
  {
    id: '2',
    title: 'Linen Wingback',
    slug: 'linen-wingback',
    piece_type: 'Reupholstered wingback chair',
    category: 'upholstery',
    price_zar: 3200,
    status: 'available',
    year: '2025',
    materials: 'Wood frame, cream linen, down-filled',
    dimensions: { width_cm: 85, height_cm: 95, depth_cm: 80 },
    description: 'Classic wingback reupholstered in soft cream linen.',
    before_image: { url: 'https://picsum.photos/seed/before-wingback/900/700' },
    after_images: [
      { image: { url: 'https://picsum.photos/seed/after-wingback/900/700' } },
    ],
    featured: false,
  },
  {
    id: '3',
    title: 'Oak Writing Desk',
    slug: 'oak-desk',
    piece_type: 'Restored oak desk',
    category: 'wood',
    price_zar: 5800,
    status: 'sold',
    year: '2024',
    materials: 'Solid oak, refinished, new leather inlay',
    dimensions: { width_cm: 140, height_cm: 75, depth_cm: 70 },
    description: 'Solid oak desk with newly inlaid leather desktop.',
    before_image: { url: 'https://picsum.photos/seed/before-desk/800/900' },
    after_images: [
      { image: { url: 'https://picsum.photos/seed/after-desk/800/900' } },
    ],
    featured: false,
  },
]
