// This file is auto-generated by Payload when you run `next build` or `next dev`.
// Do not edit manually. It maps custom component paths to their resolved imports
// so the Admin UI can dynamically load them without full-bundle re-imports.
//
// On first run: `npm run dev` will generate the real content of this file.
// The empty export below is the initial stub that satisfies the import in page.tsx.

export const importMap = {}
